### ISSUE TITLE
contestのカラム追加

### ISSUE THREAD

**Issue by teruto725** [KACG-D/CodeParty-Backend#3]
contestにチュートリアル情報取得用のtutorial : str カラムと画像表示用のimage: strカラムを追加してほしいです。
imageについてurl叩いたら画像撮ってこれるみたいなことってできる？
https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

**Comment by disk-12** [comment]
contestのthumbとかuserのiconは画像のURL
