### ISSUE TITLE
PATCH users/.:id/updateを実装してほしい

### ISSUE THREAD

**Issue by teruto725** [KACG-D/CodeParty-Backend#5]
user情報を更新するためのエンドポイントをいただけるとありがたいです。
これでavatorの更新も行う予定です。
data { 
   "name": "string",
  "password": "string",
  "email": "string",
  "avator": "string",
}

**Comment by disk-12** [comment]
現状はアバター（画像）だけ更新するやつがあった
/users/update/に認証ありポストで実装します

**Comment by disk-12** [comment]
現状画像だけポストするやつは画像アップロード用やわ
users/update/のavotorはURLでいいんかな
とりあえずそれで実装します

**Comment by disk-12** [comment]
すり合わせないと分からんから/users/update/の方はavotor以外の更新にした（userのcreateと同じパラメータのpost）．

**Comment by teruto725** [comment]
avatorはファイルでお願いしたい

**Comment by disk-12** [comment]
ファイルにしてOptionalとかなんかな
できるか分からんけど

**Comment by disk-12** [comment]
ログインいるからdocsではできんかったけど実装した
fileはNoneなら無視してるけどOptionalになってるか分からん
