### ISSUE TITLE
User avatorのデフォルト値の設定。

### ISSUE THREAD

**Issue by teruto725** [KACG-D/CodeParty-Backend#6]
User avatorで初期画像が設定されてるといいなと思います。
（急ぎではないです）

**Comment by disk-12** [comment]
nullにしてるからフロントでできると思ったけど，デフォルトのほうが条件分岐なくてよさそうやね

**Comment by disk-12** [comment]
デフォルトは適当なアイコンにした
（新規ユーザーから）
